---
# GitHub Workflow doc:
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

name: Build

on:
  push:
    branches:
      - "**"

jobs:
  masscompile:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Pull LabVIEW container image
        run: docker pull nationalinstruments/labview:latest-windows
      - name: Run LabVIEWCLI MassCompile
        run: >
          docker run --rm
          -v "${{ github.workspace }}:C:\workspace"
          nationalinstruments/labview:latest-windows
          LabVIEWCLI -LogToConsole TRUE -OperationName MassCompile
          -DirectoryToCompile "C:\workspace\src" -Headless
